#!/usr/bin/env python3
"""
merge_dictionary.py — Reconcile local-components.md with vue_indexer.py JSON output.

Contract
--------
  stdin   : vue_indexer JSON (when --new-data is omitted)
  stdout  : summary JSON: {"total","inserted","updated","deleted","scanned",
                            "parse_warnings","removed"}
  stderr  : per-row human-readable messages (DEL / ADD lines)
  --output: path where the reconciled local-components.md is written (REQUIRED)
  exit 0  : success
  exit 1  : fatal error

Upsert rules
------------
  DELETE : file in old index but not on disk  → row removed
  UPDATE : file in both                        → props + used_in refreshed; purpose preserved
  INSERT : file on disk but not in old index   → new row with purpose_hint from indexer

Stdlib only. Python 3.8+. No pip dependencies.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def strip_backticks(s: str) -> str:
    return s.strip().strip('`').strip()


def format_props(props: str) -> str:
    return '—' if (not props or props == '—') else f'`{props}`'


def format_used_in(paths: list) -> str:
    return '—' if not paths else ', '.join(f'`{p}`' for p in paths)


# ---------------------------------------------------------------------------
# Old index parser
# ---------------------------------------------------------------------------

def parse_old_index(filepath: str | None) -> dict:
    """
    Parse existing local-components.md Markdown table.
    Returns dict keyed by file_path (string, backticks stripped).
    Tolerant of header rows, separator rows, and comment lines.
    """
    rows: dict = {}
    if not filepath:
        return rows
    p = Path(filepath)
    if not p.exists():
        return rows

    for line in p.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line.startswith('|'):
            continue
        # Skip separator rows: |---|---|...|
        if re.match(r'^\|[\s\-|]+\|$', line):
            continue
        # Split and strip, discard the empty strings from leading/trailing |
        cells = [c.strip() for c in line.split('|')][1:-1]
        if len(cells) < 5:
            continue
        file_path = strip_backticks(cells[1])
        # Column 1 must be a .vue path — guards against header rows
        if not file_path.endswith('.vue'):
            continue
        rows[file_path] = {
            'display_name': strip_backticks(cells[0]),
            'file_path': file_path,
            'props': strip_backticks(cells[2]),
            'purpose': cells[3].strip(),
        }
    return rows


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------

def render_table(rows: list) -> str:
    lines = [
        '# Local Component Index',
        '',
        f'> Auto-generated by /index-components. Last updated: {date.today()}.',
        '> Props are always overwritten from source on each run.',
        '> Edit the Purpose column manually — it is preserved across runs.',
        '',
        '| Component | File path | Props | Purpose | Used In |',
        '|-----------|-----------|-------|---------|---------|',
    ]
    for row in rows:
        lines.append(
            f'| `{row["display_name"]}` '
            f'| `{row["file_path"]}` '
            f'| {format_props(row["props"])} '
            f'| {row["purpose"]} '
            f'| {format_used_in(row["used_in"])} |'
        )
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description='Reconcile local-components.md with vue_indexer JSON.',
    )
    parser.add_argument('--old-index', default=None,
                        help='Path to existing local-components.md (optional)')
    parser.add_argument('--new-data', default=None,
                        help='Path to vue_indexer JSON (reads stdin if omitted)')
    parser.add_argument('--output', required=True,
                        help='Output path for the reconciled local-components.md')
    args = parser.parse_args()

    # -- Read new-data JSON ------------------------------------------------
    if args.new_data:
        try:
            raw = Path(args.new_data).read_text(encoding='utf-8')
        except Exception as e:
            print(f'ERROR: Cannot read --new-data: {e}', file=sys.stderr)
            sys.exit(1)
    else:
        raw = sys.stdin.read()

    try:
        new_data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f'ERROR: Invalid JSON from indexer: {e}', file=sys.stderr)
        sys.exit(1)

    new_lookup: dict = {c['file_path']: c for c in new_data.get('components', [])}

    # -- Parse old index (read BEFORE opening output for write) ------------
    old_rows: dict = parse_old_index(args.old_index)

    # -- Reconcile ---------------------------------------------------------
    output_rows: list = []
    removed_names: list = []
    n_inserted = n_updated = n_deleted = 0

    # DELETE + UPDATE pass
    for fpath, old in old_rows.items():
        if fpath in new_lookup:
            new_comp = new_lookup[fpath]
            output_rows.append({
                'display_name': old['display_name'],    # preserve (incl. disambiguation suffix)
                'file_path': fpath,
                'props': new_comp['props'],              # always refresh from source
                'purpose': old['purpose'],               # preserve manual edits
                'used_in': new_comp['used_in'],          # always refresh
            })
            n_updated += 1
        else:
            removed_names.append(f'{old["display_name"]} ({fpath})')
            print(f'  DEL  {old["display_name"]} ({fpath})', file=sys.stderr)
            n_deleted += 1

    # INSERT pass
    for fpath, new_comp in new_lookup.items():
        if fpath not in old_rows:
            output_rows.append({
                'display_name': new_comp['name'],
                'file_path': fpath,
                'props': new_comp['props'],
                'purpose': new_comp['purpose_hint'],
                'used_in': new_comp['used_in'],
            })
            print(f'  ADD  {new_comp["name"]} ({fpath})', file=sys.stderr)
            n_inserted += 1

    # Sort by file path (alphabetical)
    output_rows.sort(key=lambda r: r['file_path'])

    # -- Write output file -------------------------------------------------
    out_path = Path(args.output)
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(render_table(output_rows), encoding='utf-8')
    except Exception as e:
        print(f'ERROR: Cannot write output: {e}', file=sys.stderr)
        sys.exit(1)

    # -- Emit summary JSON to stdout ---------------------------------------
    summary = {
        'total': len(output_rows),
        'inserted': n_inserted,
        'updated': n_updated,
        'deleted': n_deleted,
        'scanned': new_data.get('scanned', len(new_lookup)),
        'parse_warnings': len(new_data.get('parse_warnings', [])),
        'removed': removed_names,
    }
    print(json.dumps(summary, ensure_ascii=False))


if __name__ == '__main__':
    main()
